letters = {
    "A": [
        "  A  ",
        " A A ",
        "A   A",
        "AAAAA",
        "A   A",
        "A   A",
    ],
    "B": [
        "BBBB ",
        "B   B",
        "BBBB ",
        "B   B",
        "B   B",
        "BBBB ",
    ],
    "C": [
        " CCC ",
        "C   C",
        "C    ",
        "C    ",
        "C   C",
        " CCC ",
    ],
    "D": [
        "DDDD ",
        "D   D",
        "D   D",
        "D   D",
        "D   D",
        "DDDD ",
    ],
    "E": [
        "EEEEE",
        "E    ",
        "EEEEE",
        "E    ",
        "E    ",
        "EEEEE",
    ],
    "F": [
        "FFFFF",
        "F    ",
        "FFFFF",
        "F    ",
        "F    ",
        "F    ",
    ],
    "G": [
        " GGG ",
        "G    ",
        "G GGG",
        "G   G",
        "G   G",
        " GGG ",
    ],
    "H": [
        "H   H",
        "H   H",
        "HHHHH",
        "H   H",
        "H   H",
        "H   H",
    ],
    "I": [
        "IIIII",
        "  I  ",
        "  I  ",
        "  I  ",
        "  I  ",
        "IIIII",
    ],
    "J": [
        "JJJJJ",
        "    J",
        "    J",
        "    J",
        "J   J",
        " JJJ ",
    ],
    "K": [
        "K   K",
        "K  K ",
        "KKK  ",
        "K  K ",
        "K   K",
        "K    ",
    ],
    "L": [
        "L    ",
        "L    ",
        "L    ",
        "L    ",
        "L    ",
        "LLLLL",
    ],
    "M": [
        "M   M",
        "MM MM",
        "M M M",
        "M   M",
        "M   M",
        "M   M",
    ],
    "N": [
        "N   N",
        "NN  N",
        "N N N",
        "N  NN",
        "N   N",
        "N   N",
    ],
    "O": [
        " OOO ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
    ],
    "P": [
        "PPPP ",
        "P   P",
        "P   P",
        "PPPP ",
        "P    ",
        "P    ",
    ],
    "Q": [
        " QQQ ",
        "Q   Q",
        "Q   Q",
        "Q Q Q",
        "Q  Q ",
        " QQ Q",
    ],
    "R": [
        "RRRR ",
        "R   R",
        "R   R",
        "RRRR ",
        "R  R ",
        "R   R",
    ],
    "S": [
        " SSS ",
        "S    ",
        " SSS ",
        "    S",
        "S   S",
        " SSS ",
    ],
    "T": [
        "TTTTT",
        "  T  ",
        "  T  ",
        "  T  ",
        "  T  ",
        "  T  ",
    ],
    "U": [
        "U   U",
        "U   U",
        "U   U",
        "U   U",
        "U   U",
        " UUU ",
    ],
    "V": [
        "V   V",
        "V   V",
        "V   V",
        "V   V",
        " V V ",
        "  V  ",
    ],
    "W": [
        "W   W",
        "W   W",
        "W   W",
        "W W W",
        "WW WW",
        "W   W",
    ],
    "X": [
        "X   X",
        " X X ",
        "  X  ",
        " X X ",
        "X   X",
        "X   X",
    ],
    "Y": [
        "Y   Y",
        " Y Y ",
        "  Y  ",
        "  Y  ",
        "  Y  ",
        "  Y  ",
    ],
    "Z": [
        "ZZZZZ",
        "    Z",
        "   Z ",
        "  Z  ",
        " Z   ",
        "ZZZZZ",
    ],
    "a": [
        " aaa ",
        "    a",
        " aaaa",
        "a   a",
        " aaaa",
    ],
    "b": [
        "b    ",
        "b    ",
        "b    ",
        "bbbb ",
        "b   b",
        "b   b",
        "bbbb ",
    ],
    "c": [
        " ccc ",
        "c    ",
        "c    ",
        "c    ",
        " ccc ",
    ],
    "d": [
        "    d",
        "    d",
        "    d",
        " dddd",
        "d   d",
        "d   d",
        " dddd",
    ],
    "e": [
        " eee ",
        "e   e",
        "eeeee",
        "e    ",
        " eeee",
    ],
    "f": [
        " fff ",
        "f   f",
        "f    ",
        "ffff ",
        "f    ",
        "f    ",
        "f    ",
    ],
    "g": [
        " ggg ",
        "g   g",
        " gggg",
        "    g",
        " ggg ",
    ],
    "h": [
        "h    ",
        "h    ",
        "h    ",
        "hhhh ",
        "h   h",
        "h   h",
        "h   h",
    ],
    "i": [
        "  i  ",
        "     ",
        "  i  ",
        "  i  ",
        "  i  ",
        "  i  ",
    ],
    "j": [
        "    j",
        "     ",
        "   jj",
        "    j",
        "j   j",
        " jjj ",
    ],
    "k": [
        "k    ",
        "k    ",
        "k   k",
        "k  k ",
        "kkk  ",
        "k  k ",
        "k   k",
    ],
    "l": [
        " l   ",
        " l   ",
        " l   ",
        " l   ",
        " llll",
    ],
    "m": [
        "mmmmmmm",
        "m  m  m",
        "m  m  m",
        "m  m  m",
        "m  m  m",
    ],
    "n": [
        "n n n",
        "nn  n",
        "n   n",
        "n   n",
        "n   n",
    ],
    "o": [
        " ooo ",
        "o   o",
        "o   o",
        "o   o",
        " ooo ",
    ],
    "p": [
        "pppp ",
        "p   p",
        "pppp ",
        "p    ",
        "p    ",
    ],
    "q": [
        " qqqq",
        "q   q",
        " qqqq",
        "    q",
        "    q",
    ],
    "r": [
        "rrrr ",
        "r   r",
        "r    ",
        "r    ",
        "r    ",
    ],
    "s": [
        " ssss",
        "s    ",
        " sss ",
        "    s",
        "ssss ",
    ],
    "t": [
        " t   ",
        " t   ",
        "ttttt",
        " t   ",
        " t   ",
        " t   ",
        "  t t",
    ],
    "u": [
        "u   u",
        "u   u",
        "u   u",
        "u   u",
        " uuuu",
    ],
    "v": [
        "v   v",
        "v   v",
        "v   v",
        " v v ",
        "  v  ",
    ],
    "w": [
        "w   w",
        "w   w",
        "w   w",
        "w w w",
        "ww ww",
        "w   w",
    ],
    "x": [
        "x   x",
        " x x ",
        "  x  ",
        " x x ",
        "x   x",
    ],
    "y": [
        "y   y",
        " y y ",
        "  y  ",
        "  y  ",
        "  y  ",
    ],
    "z": [
        "zzzzz",
        "   z ",
        "  z  ",
        " z   ",
        "zzzzz",
    ],
}
